import { Alert } from "./types";

// Alertas pré-definidos (futuramente gerados dinamicamente cruzando módulos)
export const mockAlerts: Alert[] = [
  // ── Críticos ────────────────────────────────────────────────────────────────
  {
    id: "alr-001",
    companyId: "emp-004",
    title: "FGTS Digital vencido – Metalúrgica Santa Fé",
    description: "A guia de FGTS Digital referente à competência 04/2026 venceu em 07/05/2026 sem confirmação de pagamento. Sujeito a multa e juros.",
    severity: "Crítico",
    category: "Obrigação Fiscal",
    createdAt: "2026-05-08T08:00:00",
    dueDate: "2026-05-07",
    read: false,
    actionLabel: "Ver Obrigação",
    actionTarget: "OBRIGACOES_FISCAIS",
    sourceModule: "Obrigações Fiscais",
  },
  {
    id: "alr-002",
    companyId: "emp-002",
    title: "DARF IRPJ vencido – Tech Solutions",
    description: "DARF de estimativa mensal do IRPJ (05/2026) venceu em 30/05/2026 sem evidência de recolhimento. Verificar se houve pagamento externo à plataforma.",
    severity: "Crítico",
    category: "Pendência Fiscal",
    createdAt: "2026-06-01T08:00:00",
    dueDate: "2026-05-30",
    read: false,
    actionLabel: "Ver Obrigação",
    actionTarget: "OBRIGACOES_FISCAIS",
    sourceModule: "Obrigações Fiscais",
  },
  {
    id: "alr-003",
    companyId: "emp-004",
    title: "Certificado Digital A1 expira em 7 dias – Metalúrgica Santa Fé",
    description: "O certificado A1 da empresa vence em 25/06/2026. Após o vencimento, a empresa ficará impedida de assinar documentos eletrônicos, transmitir eSocial e emitir NF-e.",
    severity: "Crítico",
    category: "Certificado Digital",
    createdAt: "2026-06-18T09:00:00",
    dueDate: "2026-06-25",
    read: false,
    actionLabel: "Ver Empresa",
    actionTarget: "EMPRESAS",
    sourceModule: "Empresas",
  },

  // ── Atenção ──────────────────────────────────────────────────────────────────
  {
    id: "alr-004",
    companyId: "emp-001",
    title: "DAS vence em 2 dias – Pão Dourado",
    description: "O DAS do Simples Nacional (05/2026) no valor de R$ 1.840,50 vence em 20/06/2026. Providenciar pagamento para evitar exclusão do Simples.",
    severity: "Atenção",
    category: "Obrigação Fiscal",
    createdAt: "2026-06-18T07:00:00",
    dueDate: "2026-06-20",
    read: false,
    actionLabel: "Ver Obrigação",
    actionTarget: "OBRIGACOES_FISCAIS",
    sourceModule: "Obrigações Fiscais",
  },
  {
    id: "alr-005",
    companyId: "emp-002",
    title: "ECD – prazo se aproxima (12 dias) – Tech Solutions",
    description: "A Escrituração Contábil Digital (ECD) do exercício 2025 deve ser transmitida até 30/06/2026 via SPED. Confirmar fechamento contábil com o responsável.",
    severity: "Atenção",
    category: "Obrigação Fiscal",
    createdAt: "2026-06-17T09:00:00",
    dueDate: "2026-06-30",
    read: true,
    actionLabel: "Ver Obrigação",
    actionTarget: "OBRIGACOES_FISCAIS",
    sourceModule: "Obrigações Fiscais",
  },
  {
    id: "alr-006",
    companyId: "emp-002",
    title: "Certificado Digital A1 expira em 17 dias – Tech Solutions",
    description: "O certificado A1 vence em 05/07/2026. Iniciar processo de renovação com a AC certificadora para evitar interrupção de serviços digitais.",
    severity: "Atenção",
    category: "Certificado Digital",
    createdAt: "2026-06-15T10:00:00",
    dueDate: "2026-07-05",
    read: true,
    actionLabel: "Ver Empresa",
    actionTarget: "EMPRESAS",
    sourceModule: "Empresas",
  },
  {
    id: "alr-007",
    companyId: "emp-002",
    title: "DCTFWeb vence em 27 dias – Tech Solutions",
    description: "DCTFWeb referente às contribuições de 05/2026 no valor de R$ 8.420,00 deve ser transmitida e paga até 15/07/2026.",
    severity: "Atenção",
    category: "Obrigação Fiscal",
    createdAt: "2026-06-14T08:00:00",
    dueDate: "2026-07-15",
    read: true,
    actionLabel: "Ver Obrigação",
    actionTarget: "OBRIGACOES_FISCAIS",
    sourceModule: "Obrigações Fiscais",
  },

  // ── Informativos ────────────────────────────────────────────────────────────
  {
    id: "alr-008",
    companyId: "emp-002",
    title: "Nota Fiscal nº 000123 cancelada – Tech Solutions",
    description: "A NFS-e nº 000123 emitida para Rede Globo S.A. foi cancelada. A nota corretora nº 000126 está em processo de emissão.",
    severity: "Informativo",
    category: "Nota Fiscal",
    createdAt: "2026-05-28T14:30:00",
    read: true,
    actionLabel: "Ver Nota",
    actionTarget: "NOTAS_FISCAIS",
    sourceModule: "Notas Fiscais",
  },
  {
    id: "alr-009",
    title: "Atualização: nova versão do layout eSocial (S-1.3)",
    description: "A Receita Federal publicou nota técnica com alterações no leiaute do eSocial versão S-1.3, com vigência a partir de 01/09/2026. Nenhuma ação imediata necessária.",
    severity: "Informativo",
    category: "Sistema",
    createdAt: "2026-06-10T11:00:00",
    read: true,
    sourceModule: "Sistema",
  },
];
