import { Company } from "./types";

export const mockCompanies: Company[] = [
  {
    id: "emp-001",
    razaoSocial: "Padaria Pão Dourado Ltda",
    nomeFantasia: "Pão Dourado",
    cnpj: "12.345.678/0001-90",
    cnae: "4721-1/02",
    cnaeDescricao: "Padaria e confeitaria com predominância de produção própria",
    regime: "Simples Nacional",
    responsavel: "Marcos Vinícius Silva",
    contadorResponsavel: "Ana Paula Ferreira",
    status: "Ativa",
    dataAbertura: "2018-03-14",
    socios: [{ id: "soc-1", nome: "Marcos Vinícius Silva", cpf: "123.456.789-00", participacao: 100 }],
    email: "contato@paodourado.com.br",
    telefone: "(11) 4002-8922",
    endereco: "Rua das Acácias, 245 - São Paulo/SP",
    certificadoDigitalValidade: "2026-09-30",
  },
  {
    id: "emp-002",
    razaoSocial: "Tech Solutions Desenvolvimento de Software S.A.",
    nomeFantasia: "Tech Solutions",
    cnpj: "23.456.789/0001-11",
    cnae: "6201-5/01",
    cnaeDescricao: "Desenvolvimento de programas de computador sob encomenda",
    regime: "Lucro Presumido",
    responsavel: "Fernanda Lima",
    contadorResponsavel: "Carlos Eduardo Souza",
    status: "Ativa",
    dataAbertura: "2015-07-22",
    socios: [
      { id: "soc-2", nome: "Fernanda Lima", cpf: "234.567.890-11", participacao: 60 },
      { id: "soc-3", nome: "Rodrigo Almeida", cpf: "345.678.901-22", participacao: 40 },
    ],
    email: "financeiro@techsolutions.com.br",
    telefone: "(11) 3055-7700",
    endereco: "Av. Paulista, 1100, Conj. 502 - São Paulo/SP",
    certificadoDigitalValidade: "2026-07-05",
  },
  {
    id: "emp-003",
    razaoSocial: "João Pedro Consultoria MEI",
    nomeFantasia: "JP Consultoria",
    cnpj: "34.567.890/0001-22",
    cnae: "7020-4/00",
    cnaeDescricao: "Atividades de consultoria em gestão empresarial",
    regime: "MEI",
    responsavel: "João Pedro Santos",
    contadorResponsavel: "Ana Paula Ferreira",
    status: "Ativa",
    dataAbertura: "2022-01-10",
    socios: [{ id: "soc-4", nome: "João Pedro Santos", cpf: "456.789.012-33", participacao: 100 }],
    email: "joaopedro@jpconsultoria.com.br",
    telefone: "(11) 98877-6655",
    endereco: "Rua Vergueiro, 980 - São Paulo/SP",
  },
  {
    id: "emp-004",
    razaoSocial: "Indústria Metalúrgica Santa Fé Ltda",
    nomeFantasia: "Metalúrgica Santa Fé",
    cnpj: "45.678.901/0001-33",
    cnae: "2542-0/00",
    cnaeDescricao: "Fabricação de artigos de serralheria",
    regime: "Lucro Real",
    responsavel: "Patrícia Mendes",
    contadorResponsavel: "Carlos Eduardo Souza",
    status: "Em Encerramento",
    dataAbertura: "2010-11-02",
    socios: [{ id: "soc-5", nome: "Patrícia Mendes", cpf: "567.890.123-44", participacao: 100 }],
    email: "patricia@santafemetal.com.br",
    telefone: "(11) 4112-9090",
    endereco: "Rod. Anhanguera, km 32 - Jundiaí/SP",
    certificadoDigitalValidade: "2026-06-25",
  },
];
